const fakeMails = [ { sender: "Railway", subject: "Object Storage, Bounty Cash Withdrawals", date: "Sep 27" },
    { sender: "LeetCode", subject: "LeetCode Weekly Digest - New updates and features", date: "Sep 26" },
    { sender: "hirist.tech", subject: "Job Opportunity: PHP Developer - Laravel (1-3 yrs)", date: "Sep 26" },
    { sender: "Naukri Campus", subject: "Varun Joshi, New Job Opportunities for Developer", date: "Sep 26" },
    { sender: "Indeed", subject: "Backend Developer position was closed", date: "Sep 25" },
    { sender: "LinkedIn", subject: "80 year old gun that's still winning battles", date: "Sep 25" },
    { sender: "Render", subject: "Upcoming changes to Render's outbound IPs", date: "Sep 26" },
    { sender: "Railway", subject: "Object Storage, Bounty Cash Withdrawals", date: "Sep 27" },
    { sender: "LeetCode", subject: "LeetCode Weekly Digest - New updates and features", date: "Sep 26" },
    { sender: "hirist.tech", subject: "Job Opportunity: PHP Developer - Laravel (1-3 yrs)", date: "Sep 26" },
    { sender: "Naukri Campus", subject: "Varun Joshi, New Job Opportunities for Developer", date: "Sep 26" },
    { sender: "Indeed", subject: "Backend Developer position was closed", date: "Sep 25" },
    { sender: "LinkedIn", subject: "80 year old gun that's still winning battles", date: "Sep 25" },
    { sender: "Render", subject: "Upcoming changes to Render's outbound IPs", date: "Sep 26" },
    { sender: "Railway", subject: "Object Storage, Bounty Cash Withdrawals", date: "Sep 27" },
    { sender: "LeetCode", subject: "LeetCode Weekly Digest - New updates and features", date: "Sep 26" },
    { sender: "hirist.tech", subject: "Job Opportunity: PHP Developer - Laravel (1-3 yrs)", date: "Sep 26" },
    { sender: "Naukri Campus", subject: "Varun Joshi, New Job Opportunities for Developer", date: "Sep 26" },
    { sender: "Indeed", subject: "Backend Developer position was closed", date: "Sep 25" },
    { sender: "LinkedIn", subject: "80 year old gun that's still winning battles", date: "Sep 25" },
    { sender: "Render", subject: "Upcoming changes to Render's outbound IPs", date: "Sep 26" },
    { sender: "Railway", subject: "Object Storage, Bounty Cash Withdrawals", date: "Sep 27" },
    { sender: "LeetCode", subject: "LeetCode Weekly Digest - New updates and features", date: "Sep 26" },
    { sender: "hirist.tech", subject: "Job Opportunity: PHP Developer - Laravel (1-3 yrs)", date: "Sep 26" },
    { sender: "Naukri Campus", subject: "Varun Joshi, New Job Opportunities for Developer", date: "Sep 26" },
    { sender: "Indeed", subject: "Backend Developer position was closed", date: "Sep 25" },
    { sender: "LinkedIn", subject: "80 year old gun that's still winning battles", date: "Sep 25" },
    { sender: "Render", subject: "Upcoming changes to Render's outbound IPs", date: "Sep 26" },
    { sender: "Railway", subject: "Object Storage, Bounty Cash Withdrawals", date: "Sep 27" },
    { sender: "LeetCode", subject: "LeetCode Weekly Digest - New updates and features", date: "Sep 26" },
    { sender: "hirist.tech", subject: "Job Opportunity: PHP Developer - Laravel (1-3 yrs)", date: "Sep 26" },
    { sender: "Naukri Campus", subject: "Varun Joshi, New Job Opportunities for Developer", date: "Sep 26" },
    { sender: "Indeed", subject: "Backend Developer position was closed", date: "Sep 25" },
    { sender: "LinkedIn", subject: "80 year old gun that's still winning battles", date: "Sep 25" },
    { sender: "Render", subject: "Upcoming changes to Render's outbound IPs", date: "Sep 26" },
    { sender: "Railway", subject: "Object Storage, Bounty Cash Withdrawals", date: "Sep 27" },
    { sender: "LeetCode", subject: "LeetCode Weekly Digest - New updates and features", date: "Sep 26" },
    { sender: "hirist.tech", subject: "Job Opportunity: PHP Developer - Laravel (1-3 yrs)", date: "Sep 26" },
    { sender: "Naukri Campus", subject: "Varun Joshi, New Job Opportunities for Developer", date: "Sep 26" },
    { sender: "Indeed", subject: "Backend Developer position was closed", date: "Sep 25" },
    { sender: "LinkedIn", subject: "80 year old gun that's still winning battles", date: "Sep 25" },
    { sender: "Render", subject: "Upcoming changes to Render's outbound IPs", date: "Sep 26" },
    { sender: "Railway", subject: "Object Storage, Bounty Cash Withdrawals", date: "Sep 27" },
    { sender: "LeetCode", subject: "LeetCode Weekly Digest - New updates and features", date: "Sep 26" },
    { sender: "hirist.tech", subject: "Job Opportunity: PHP Developer - Laravel (1-3 yrs)", date: "Sep 26" },
    { sender: "Naukri Campus", subject: "Varun Joshi, New Job Opportunities for Developer", date: "Sep 26" },
    { sender: "Indeed", subject: "Backend Developer position was closed", date: "Sep 25" },
    { sender: "LinkedIn", subject: "80 year old gun that's still winning battles", date: "Sep 25" },
    { sender: "Render", subject: "Upcoming changes to Render's outbound IPs", date: "Sep 26" },
    { sender: "Railway", subject: "Object Storage, Bounty Cash Withdrawals", date: "Sep 27" },
    { sender: "LeetCode", subject: "LeetCode Weekly Digest - New updates and features", date: "Sep 26" },
    { sender: "hirist.tech", subject: "Job Opportunity: PHP Developer - Laravel (1-3 yrs)", date: "Sep 26" },
    { sender: "Naukri Campus", subject: "Varun Joshi, New Job Opportunities for Developer", date: "Sep 26" },
    { sender: "Indeed", subject: "Backend Developer position was closed", date: "Sep 25" },
    { sender: "LinkedIn", subject: "80 year old gun that's still winning battles", date: "Sep 25" },
    { sender: "Render", subject: "Upcoming changes to Render's outbound IPs", date: "Sep 26" },


];


    export {fakeMails}